from scale_services.scale_service import AbstractScaleService

from scale_services.neural_service import NeuralScaleService
from scale_services.interpolation_service import InterpolationScaleService, InterpolMethod